- name: Ansible
  hosts: all
  become: true
  tasks:
    - name: Add Ansible repo
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
    - name: Ensure software-properties-common is present
      ansible.builtin.apt:
        name: software-properties-common
        update_cache: yes
