- name: Base dirs
  hosts: all
  become: true
  tasks:
    - name: Ensure downloads dir exists
      ansible.builtin.file:
        path: /downloads
        state: directory
        owner: root
        group: root
        mode: "0777"
    - name: Ensure ansible_state dir exists
      ansible.builtin.file:
        path: /ansible_state
        state: directory
        owner: root
        group: root
        mode: "0666"
