- name: Set UNIX aliases
  hosts: all
  become: true
  tasks:
    - name: Add aliases to .profile
      ansible.builtin.blockinfile:
        path: /home/vagrant/.profile
        block: |
          ## Profile aliases
          # Show hidden files #
          alias l.='ls -d .* --color=auto'
          ## a quick way to get out of current directory
          alias ..='cd ..'
          alias ...='cd ../../../'
          alias ....='cd ../../../../'
          alias .....='cd ../../../../'
          alias .4='cd ../../../../'
          alias .5='cd ../../../../..'
          ## handy short cuts
          alias h='history'
          alias j='jobs -l'
          alias path='echo -e ${PATH//:/\\n}'
          alias now='date +"%T"'
          alias nowtime=now
          alias nowdate='date +"%d-%m-%Y"'
          alias getusers='cut -d: -f1 /etc/passwd'
          ## Stop after sending count ECHO_REQUEST packets #
          alias ping='ping -c 5'
          ## Do not wait interval 1 second, go fast #
          alias fastping='ping -c 100 -s.2'
          ## Use netstat command to quickly list all TCP/UDP port on the server:
          alias ports='netstat -tulanp'
          ## pass options to free ##
          alias meminfo='free -m -l -t'
          ## get top process eating memory
          alias psmem='ps auxf | sort -nr -k 4'
          alias psmem10='ps auxf | sort -nr -k 4 | head -10'
          ## get top process eating cpu ##
          alias pscpu='ps auxf | sort -nr -k 3'
          alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
          ## Get server cpu info ##
          ## older system use /proc/cpuinfo ##
          alias cpuinfo='less /proc/cpuinfo'
          ## get GPU ram on desktop / laptop##
          alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
          alias wget='wget -c'
