- name: Update and upgrade
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day