- name: Go
  hosts: all
  become: true
  tasks:
    - name: Install go
      community.general.snap:
        name: go
        classic: true
    - name: Set go bin path
      ansible.builtin.lineinfile:
        path: /home/vagrant/.profile
        backup: true
        create: true
        line: PATH=$PATH:/home/vagrant/go/bin