- name: Python Anaconda
  hosts: all
  become: true
  pre_tasks:
    # For other versions of Ubuntu (e.g. 22.04), you may need the deadsnakes ppa to install some python versions
    - name: Add deadsnakes repo
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
    # The version below may change depending on the Anaconda version
    # See the docs in the link below:
    # https://www.anaconda.com/download#downloads
    # https://www.digitalocean.com/community/tutorials/how-to-install-the-anaconda-python-distribution-on-ubuntu-20-04
    - name: Ensure needed python version for Anaconda3 is present
      ansible.builtin.apt:
        name: python3.10
        update_cache: yes
    - name: Download Anaconda3 installer
      ansible.builtin.command:
        chdir: /downloads
        cmd: curl https://repo.anaconda.com/archive/Anaconda3-2023.03-1-Linux-x86_64.sh --output anaconda.sh
        creates: anaconda.sh
    - name: Make the installer executable
      ansible.builtin.file:
        path: /downloads/anaconda.sh
        mode: "0777"
        owner: root
        group: root
    - name: Output the hash checksum to a file
      ansible.builtin.shell:
        chdir: /downloads
        cmd: sha256sum anaconda.sh > anaconda_checksum.txt
        creates: anaconda_checksum.txt
  tasks:
    - name: Install Anaconda3
      ansible.builtin.shell:
        chdir: /downloads
        cmd: ./anaconda.sh -b -p /anaconda3
        creates: /anaconda3/condabin/conda
  post_tasks:
    - name: Create anaconda group
      ansible.builtin.group:
        name: anaconda
        system: true
    - name: Allow anaconda group to own the entire anaconda directory
      ansible.builtin.file:
        path: /anaconda3
        recurse: true
        state: directory
        group: anaconda
        mode: "0770"
    - name: Add the vagrant user to anaconda group
      ansible.builtin.user:
        name: vagrant
        append: true
        groups: anaconda
    - name: Get stats of anaconda init state
      ansible.builtin.stat:
        path: /ansible_state/anaconda_init
      register: anaconda_init
    - name: Initialize conda
      become: true
      become_user: vagrant
      ansible.builtin.shell: |
        /anaconda3/bin/activate && /anaconda3/condabin/conda init
      when: not anaconda_init.stat.exists
    - name: Register anaconda initialization state
      ansible.builtin.file:
        path: /ansible_state/anaconda_init
        state: directory
