- name: Python
  hosts: all
  become: true
  tasks:
    # Manage python versions
    # https://github.com/pyenv/pyenv
    - name: Install pyenv
      become: false
      community.general.homebrew:
        name: pyenv
    - name: Setup shell environment for pyenv
      ansible.builtin.blockinfile:
        path: /home/vagrant/.profile
        backup: true
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$($(which pyenv) init -)"
    # Manage python virtual envs
    # https://github.com/pyenv/pyenv-virtualenv
    - name: Install pyenv-virtualenv plugin
      become: false
      community.general.homebrew:
        name: pyenv-virtualenv
    - name: Setup shell environment for pyenv-virtualenv
      ansible.builtin.lineinfile:
        path: /home/vagrant/.profile
        backup: true
        line: eval "$($(which pyenv) virtualenv-init -)"
