- name: Setup MySQL
  hosts: all
  become: true
  become_user: vagrant
  # Source: https://github.com/geerlingguy/ansible-role-mysql
  pre_tasks:
    - name: Install "geerlingguy.mysql" role
      community.general.ansible_galaxy_install:
        type: role
        name: geerlingguy.mysql
  tasks:
    - name: Include "geerlingguy.mysql" role
      ansible.builtin.include_role:
        name: geerlingguy.mysql
        apply:
          become: true
          become_user: root
      vars:
        mysql_root_password: my-secret-pw
        mysql_users:
          - name: vagrant
            host: "%"
            password: my-secret-pw
            priv: "*.*:ALL"
  post_tasks:
    - name: Start service mysql, if not started
      ansible.builtin.service:
        name: mysql
        state: started
  handlers:
    - name: Restart my mysql server if config changed
      ansible.builtin.service:
        name: mysql
        state: restarted

