#! Base
- name: Base
  ansible.builtin.import_playbook: ./base/init.yml
  tags:
  - always
  - init
## Cloud providers
- name: AWS
  ansible.builtin.import_playbook: ./cloud_providers/aws_cli.yml
  tags:
  - aws
## Container tools
- name: Docker
  ansible.builtin.import_playbook: ./container_tools/docker.yml
  tags:
  - docker
- name: K8s tools
  ansible.builtin.import_playbook: ./container_tools/k8s_tools.yml
  tags:
  - k8s_tools
- name: Minikube
  ansible.builtin.import_playbook: ./container_tools/minikube.yml
  tags:
  - minikube
## Dbs
- name: MySQL
  ansible.builtin.import_playbook: ./dbs/mysql.yml
  tags:
  - mysql
- name: PostgreSQL 15
  ansible.builtin.import_playbook: ./dbs/postgreSQL/15/install.yml
  tags:
  - pg-15
## Programming languages
- name: Dotnet SDK
  ansible.builtin.import_playbook: ./programming_languages/dotnet_sdk.yml
  tags:
  - dotnet_sdk
- name: Go
  ansible.builtin.import_playbook: ./programming_languages/go.yml
  tags:
  - go
- name: NodeJS
  ansible.builtin.import_playbook: ./programming_languages/node_js.yml
  tags:
  - node_js
- name: Python Anaconda
  ansible.builtin.import_playbook: ./programming_languages/python_anaconda.yml
  tags:
  - python_anaconda
- name: Rust
  ansible.builtin.import_playbook: ./programming_languages/rust.yml
  tags:
  - rust
## Terminal
- name: Starship
  ansible.builtin.import_playbook: ./terminal/starship.yml
  tags:
  - starship
## UI
- name: Git
  ansible.builtin.import_playbook: ./ui/gui.yml
  tags:
  - gui
## Vc
- name: Git
  ansible.builtin.import_playbook: ./vc/git.yml
  tags:
  - git
- name: GitHub
  ansible.builtin.import_playbook: ./vc/git_hub.yml
  tags:
  - github