- name: Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - curl
        - ca-certificates
        - gnupg
    - name: Add Docker's GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker repo to apt (Ubuntu Jammy)
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
      when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "jammy"
    - name: Install Docker components
      ansible.builtin.apt:
        name: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Ensure docker is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
    - name: Ensure Docker group exists
      user:
        name: vagrant
        groups: docker
        append: yes