- name: Minikube
  hosts: all
  become: true
  tasks:
    - name: Get stats of /usr/local/bin/minikube
      ansible.builtin.stat:
        path: /usr/local/bin/minikube
      register: minikube_dir
    - name: Download minikube binary
      ansible.builtin.shell: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      args:
        creates: /downloads/minikube-linux-amd64
        chdir: /downloads
    - name: Install minukube
      ansible.builtin.shell: install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        chdir: /downloads
      when: not minikube_dir.stat.exists
